### ISSUE TITLE
Error in running the example

### ISSUE THREAD

**Issue by saurabhbelsare** [kanamekojima/rnnimp#1]
Hi, 

I'm trying to run the example following the instructions on the github page. I downloaded the vcf, manifest, and fasta files, and installed samtools and ran the test_data_preparation.py script, which completed sucessfully. When I try to run the imputation with the command in example.sh, however, I get the following error: 

TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

_Traceback (most recent call last):_
  _File "scripts/imputation.py", line 197, in <module>
    main()
  File "scripts/imputation.py", line 193, in main
    args.num_threads)
  File "scripts/imputation.py", line 161, in imputation
    np.array(haplotype_list, dtype=np.float32), config_list,
ValueError: setting an array element with a sequence._
_TypeError: float() argument must be a string or a number, not 'list'_

_The above exception was the direct cause of the following exception:_

This above error is repeated 10 times (once for each of the 10 regions in the model_files.txt). After that, the last error is as below:

_Traceback (most recent call last):
  File "scripts/imputation.py", line 197, in <module>
    main()
  File "scripts/imputation.py", line 193, in main
    args.num_threads)
  File "scripts/imputation.py", line 161, in imputation
    np.array(haplotype_list, dtype=np.float32), config_list,
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "scripts/merge_hap_and_gen.py", line 126, in <module>
    main()
  File "scripts/merge_hap_and_gen.py", line 115, in main
    with open(gen_file) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'results/chr22_1.gen'_

It seems to me that when it is reading in the haplotype file created by test_data_preparation.py, ie chr22.hap.gz, it is reading in pairs of values instead of single values, which are being fed to np.array function as a list instead of integers, and are hence not being converted to np.float32. 

How should I fix this? 

Thank you.

**Comment by kanamekojima** [comment]
Thank you for the issue report about RNN-IMP.

In my environment where the OS is Red Hat Enterprise Linux and the version of Python is 3.5.3, I cannot reproduce the errors shown in the issue report.

If possible, could you send chr22.hap,.gz and chr22.legend.gz files you generated to the following my e-mail address?

kojima [AT] megabank [DOT] tohoku [DOT] ac [DOT] jp

I would like to check if example.sh also works with the files you generated in my environment.

I also would like to know the information about your computational environment such as OS and the version of Python, which is helpful for the error detection.

**Comment by saurabhbelsare** [comment]
I am running with Python 3.6.10 on Ubuntu 18.04.4 LTS (Bionic Beaver), with the python, tensorflow (version 1.15.0), and numpy (version 1.18.1) installations via conda. I have emailed you the files. 

Thanks for following up on this, and let me know if you need any more information from me.

**Comment by kanamekojima** [comment]
Thank you for the information of your computational environment and the input data files you sent me by e-mail.

When I was checking your input data files, I found that the errors occur if the input data does not fully contain all the SNP array markers considered in the trained models. I have fixed the scripts to handle such a case.
